---
- name: start mattermost
  service:
    name: mattermost
    state: started

- name: restart mattermost
  service:
    name: mattermost
    state: restarted

- name: restart postfix
  service:
    name: postfix
    state: restarted
